RENDER_STACK_INGEST = 'em_2d_montage_ingest'
RENDER_STACK_LENS_CORRECTED = 'em_2d_montage_lc'
RENDER_STACK_APPLY_MIPMAPS = 'em_2d_montage_apply_mipmaps'
RENDER_STACK_TILE_PAIRS = 'em_2d_montage_tile_pairs'
RENDER_STACK_POINT_MATCH = 'em_2d_montage_point_match'
RENDER_STACK_SOLVED = 'em_2d_montage_solved'