# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 23:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_camera'}
        ),
        migrations.CreateModel(
            name='Chuck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('chunk_state', models.CharField(max_length=255, null=True)),
                ('following_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuck_following_chunk', to='at_em_imaging_workflow.Chuck')),
                ('preceding_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuck_preceding_chunk', to='at_em_imaging_workflow.Chuck')),
            ],
            options={'db_table': 'development_chuck'}
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_load'}
        ),
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_microscope'}
        ),
        migrations.CreateModel(
            name='MicroscopeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_microscopetype'}
        ),
        migrations.CreateModel(
            name='RegistrationSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('workflow_state', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_registrationseries'}
        ),
        migrations.CreateModel(
            name='RenderedVolumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mipmap_directory', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_renderedvolumn'}
        ),
        migrations.CreateModel(
            name='SampleHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
                ('imaged_sections_count', models.IntegerField(null=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Load')),
            ],
            options={'db_table': 'development_sampleholder'}
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=255, null=True)),
                ('z_index', models.IntegerField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('chucks', models.ManyToManyField(related_name='sections', to='at_em_imaging_workflow.Chuck')),
                ('sample_holders', models.ManyToManyField(related_name='sample_holders', to='at_em_imaging_workflow.SampleHolder')),
            ],
            options={'db_table': 'development_section'}
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, null=True)),
                ('render_project', models.CharField(max_length=255, null=True)),
                ('render_owner', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_specimen'}
        ),
        migrations.CreateModel(
            name='Stain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_stain'}
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('storage_directory', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_study'}
        ),
        migrations.CreateModel(
            name='TileImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_directory', models.CharField(max_length=255, null=True)),
                ('workflow_state', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_tileimageset'}
        ),
        migrations.CreateModel(
            name='MontageSet',
            fields=[
                ('tileimageset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='at_em_imaging_workflow.TileImageSet')),
                ('uid', models.CharField(max_length=255, null=True)),
                ('acquisition_date', models.DateTimeField(null=True)),
                ('mipmap_directory', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_montageset'},
            bases=('at_em_imaging_workflow.tileimageset',),
        ),
        migrations.CreateModel(
            name='ReferenceSet',
            fields=[
                ('tileimageset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='at_em_imaging_workflow.TileImageSet')),
                ('uid', models.CharField(max_length=255, null=True)),
            ],
            options={'db_table': 'development_referenceset'},
            bases=('at_em_imaging_workflow.tileimageset',),
        ),
        migrations.AddField(
            model_name='tileimageset',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Camera'),
        ),
        migrations.AddField(
            model_name='tileimageset',
            name='microscope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Microscope'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Study'),
        ),
        migrations.AddField(
            model_name='section',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Specimen'),
        ),
        migrations.AddField(
            model_name='renderedvolumn',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Specimen'),
        ),
        migrations.AddField(
            model_name='microscope',
            name='microscope_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.MicroscopeType'),
        ),
        migrations.AddField(
            model_name='chuck',
            name='rendered_volumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.RenderedVolumn'),
        ),
        migrations.CreateModel(
            name='ATMontageSet',
            fields=[
                ('montageset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='at_em_imaging_workflow.MontageSet')),
                ('image_session_number', models.CharField(max_length=255, null=True)),
                ('registration_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.RegistrationSeries')),
            ],
            options={'db_table': 'development_atmontageset'},
            bases=('at_em_imaging_workflow.montageset',),
        ),
        migrations.CreateModel(
            name='EMMontageSet',
            fields=[
                ('montageset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='at_em_imaging_workflow.MontageSet')),
                ('reference_set_uid', models.CharField(max_length=255, null=True)),
                ('reference_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.ReferenceSet')),
            ],
            options={'db_table': 'development_emmontageset'},
            bases=('at_em_imaging_workflow.montageset',),
        ),
        migrations.AddField(
            model_name='montageset',
            name='sample_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.SampleHolder'),
        ),
        migrations.AddField(
            model_name='montageset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_em_imaging_workflow.Section'),
        ),
    ]
