# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_em_imaging_workflow', '0002_auto_20170831_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
