# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at_em_imaging_workflow', '0005_auto_20171111_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='rendered_volumn',
            new_name='rendered_volume',
        ),
    ]
