# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('at_em_imaging_workflow', '0008_tileimageset_metafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceset',
            name='manifest_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
