# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 18:23
from __future__ import unicode_literals

from django.db import migrations
import django_fsm

def copy_state(apps, schema_editor):
    Chunk = apps.get_model('at_em_imaging_workflow', 'Chunk')
    ReferenceSet = apps.get_model('at_em_imaging_workflow', 'ReferenceSet')
    EMMontageSet = apps.get_model('at_em_imaging_workflow', 'EMMontageSet')

    cnks = Chunk.objects.all()
    for c in cnks:
        c.object_state = c.chunk_state
        c.save()

    ref_sets = ReferenceSet.objects.all()
    for r in ref_sets:
        r.object_state = r.workflow_state
        r.save()

    msets = EMMontageSet.objects.all()
    for m in msets:
        m.object_state = m.workflow_state
        m.save()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('at_em_imaging_workflow', '0015_load_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='object_state',
            field=django_fsm.FSMField(default='INCOMPLETE', max_length=50),
        ),
        migrations.AddField(
            model_name='tileimageset',
            name='object_state',
            field=django_fsm.FSMField(default='PENDING', max_length=50),
        ),
        migrations.RunPython(
            copy_state,
            reverse_code=migrations.RunPython.noop)
    ]
