# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at_em_imaging_workflow', '0016_finite_state_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationseries',
            name='workflow_state',
        ),
        migrations.RemoveField(
            model_name='tileimageset',
            name='workflow_state',
        ),
    ]
