# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 20:38
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('at_em_imaging_workflow', '0018_load_chunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmontageset',
            name='montageset_ptr',
        ),
        migrations.RemoveField(
            model_name='atmontageset',
            name='registration_series',
        ),
        migrations.AddField(
            model_name='load',
            name='object_state',
            field=django_fsm.FSMField(default='PENDING', max_length=50),
        ),
        migrations.AlterModelTable(
            name='camera',
            table='development_camera',
        ),
        migrations.AlterModelTable(
            name='chunk',
            table='development_chunk',
        ),
        migrations.AlterModelTable(
            name='chunkassignment',
            table='development_chunkassignment',
        ),
        migrations.AlterModelTable(
            name='emmontageset',
            table='development_emmontageset',
        ),
        migrations.AlterModelTable(
            name='load',
            table='development_load',
        ),
        migrations.AlterModelTable(
            name='microscope',
            table='development_microscope',
        ),
        migrations.AlterModelTable(
            name='microscopetype',
            table='development_microscopetype',
        ),
        migrations.AlterModelTable(
            name='montageset',
            table='development_montageset',
        ),
        migrations.AlterModelTable(
            name='referenceset',
            table='development_referenceset',
        ),
        migrations.AlterModelTable(
            name='registrationseries',
            table='development_registrationseries',
        ),
        migrations.AlterModelTable(
            name='renderedvolume',
            table='development_renderedvolume',
        ),
        migrations.AlterModelTable(
            name='sampleholder',
            table='development_sampleholder',
        ),
        migrations.AlterModelTable(
            name='section',
            table='development_section',
        ),
        migrations.AlterModelTable(
            name='specimen',
            table='development_specimen',
        ),
        migrations.AlterModelTable(
            name='stain',
            table='development_stain',
        ),
        migrations.AlterModelTable(
            name='study',
            table='development_study',
        ),
        migrations.AlterModelTable(
            name='tileimageset',
            table='development_tileimageset',
        ),
        migrations.DeleteModel(
            name='ATMontageSet',
        ),
    ]
