# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceset',
            name='project_path',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tileimageset',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='development.Camera'),
        ),
        migrations.AlterField(
            model_name='tileimageset',
            name='microscope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='development.Microscope'),
        ),
    ]
