# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_montageset_overlap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('chunk_state', models.CharField(max_length=255, null=True)),
                ('following_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_following_chunk', to='development.Chunk')),
                ('preceding_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_preceding_chunk', to='development.Chunk')),
            ],
        ),
        migrations.RenameModel(
            old_name='RenderedVolumn',
            new_name='RenderedVolume',
        ),
        migrations.RemoveField(
            model_name='chuck',
            name='following_chunk',
        ),
        migrations.RemoveField(
            model_name='chuck',
            name='preceding_chunk',
        ),
        migrations.RemoveField(
            model_name='chuck',
            name='rendered_volumn',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chucks',
        ),
        migrations.DeleteModel(
            name='Chuck',
        ),
        migrations.AddField(
            model_name='chunk',
            name='rendered_volumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.RenderedVolume'),
        ),
        migrations.AddField(
            model_name='section',
            name='chunks',
            field=models.ManyToManyField(related_name='sections', to='development.Chunk'),
        ),
    ]
