# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0010_auto_20180115_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='computed_index',
            field=models.IntegerField(null=True),
        ),
    ]
