# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0012_remove chunk assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.Chunk')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='chunks',
            field=models.ManyToManyField(related_name='sections', through='development.ChunkAssignment', to='development.Chunk'),
        ),
    ]
