broker_url: pyamqp://blue_sky_user:blue_sky_user@message_queue:5672/
result_backend: rpc://
result_persistent: false
task_serializer: json
result_serializer: json
result_expires: 3600
broker_connection_timeout: 10
broker_connection_retry: false
soft_time_limit: 600
time_limit: 2400
accept_content: ['json']
worker_prefetch_multiplier: 1
timezone: US/Pacific
enable_utc: true
task_queue_max_priority: 10
broker_transport_options:
    max_retries: 3
    interval_start: 0
    interval_step: 10
    interval_max: 30
