"""
Django settings for at_em_imaging_workflow project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

APP_PACKAGE='at_em_imaging_workflow'

JOB_GRID_CLASS="at_em_imaging_workflow.views.e_m_montage_set_job_grid.EMMontageSetJobGrid"
MONITOR_TASK_MODULES=[]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = BASE_DIR

STATE_MACHINE_YML = os.path.join(
    os.path.dirname(__file__),
    'states.yml')

BASE_FILE_PATH='/allen/programs/celltypes/workgroups/em-connectomics/timf/example_data/dev'
LONG_TERM_BASE_FILE_PATH='/allen/programs/celltypes/workgroups/em-connectomics/timf/long_term/dev'
MIPMAP_FILE_PATH='/allen/programs/celltypes/workgroups/em-connectomics/timf/mipmap/dev'
DRY_RUN=True

MESSAGE_QUEUE_NAME = APP_PACKAGE
INGEST_MESSAGE_QUEUE_NAME = 'ingest_'+ MESSAGE_QUEUE_NAME
INGEST_STRATEGY='at_em_imaging_workflow.strategies.ingest_callbacks.IngestCallbacks'
WORKFLOW_MESSAGE_QUEUE_NAME = 'workflow_' + MESSAGE_QUEUE_NAME
CELERY_MESSAGE_QUEUE_NAME = 'celery_' + MESSAGE_QUEUE_NAME
MOAB_MESSAGE_QUEUE_NAME = 'moab_' + MESSAGE_QUEUE_NAME
LOCAL_MESSAGE_QUEUE_NAME = 'local_' + MESSAGE_QUEUE_NAME
BROADCAST_MESSAGE_QUEUE_NAME = 'broadcast_' + MESSAGE_QUEUE_NAME
RESULT_MESSAGE_QUEUE_NAME = 'result_' + MESSAGE_QUEUE_NAME
SPARK_MESSAGE_QUEUE_NAME='spark_' + MESSAGE_QUEUE_NAME
PBS_MESSAGE_QUEUE_NAME='pbs_' + MESSAGE_QUEUE_NAME

PBS_CONDA_HOME='/shared/utils.x86_64/python-2.7'
PBS_FINISH_MODULE='workflow_client.pbs_execution_finish'
PBS_PYTHONPATH='/data/aibstemp/timf/example_data/at_em_imaging_workflow:/data/aibstemp/timf/example_data/blue_sky_workflow_engine'
#PBS_CONDA_ENV='/allen/aibs/pipeline/image_processing/volume_assembly/conda_envs/volume_assembly/render-modules_linked'
#PBS_CONDA_ENV='/data/aibstemp/timf/example_data/blue_sky_27'
PBS_CONDA_ENV='/allen/aibs/pipeline/image_processing/volume_assembly/conda_envs/render-modules/dev'
#PBS_RESPONSE_CONDA_ENV='/data/aibstemp/timf/example_data/blue_sky_27'
PBS_RESPONSE_CONDA_ENV='/allen/aibs/pipeline/image_processing/volume_assembly/conda_envs/render-modules/dev'
BLUE_SKY_SETTINGS='/allen/aibs/pipeline/image_processing/volume_assembly/workflow_conf/dev/blue_sky_settings.yml'
STATE_MACHINE_YML='/allen/aibs/pipeline/image_processing/volume_assembly/workflow_conf/dev/states.yml'
WORKFLOW_CONFIG_YAML='/allen/aibs/pipeline/image_processing/volume_assembly/workflow_conf/dev/workflow_config.yml'

QMASTER_HOST='hpc-login.corp.alleninstitute.org'
QMASTER_PORT=22
QMASTER_USERNAME='timf'
QMASTER_CRED='/local1/git/at_em_imaging_workflow/qmaster_cred.txt'

MESSAGE_QUEUE_HOST = 'message_queue'
MESSAGE_QUEUE_USER = 'blue_sky_user'
MESSAGE_QUEUE_PASSWORD = 'blue_sky_user'
MESSAGE_QUEUE_PORT = 5672
MESSAGE_QUEUE_MONITOR_PORT = 15672
UI_HOST = 'ibs-timf-ux1.corp.alleninstitute.org'
UI_PORT = 9001
FLOWER_MONITOR_URL='http://' + UI_HOST + ":" + str(UI_PORT) + '/flower/'
RABBIT_MONITOR_URL='http://' + UI_HOST + ":" + str(UI_PORT) + '/rabbitmq/'
ADMIN_URL='http://' + UI_HOST + ':' + str(UI_PORT) + '/admin'
NOTEBOOK_URL='http://' + UI_HOST + ':' + str(UI_PORT) + '/nb/'

NOTEBOOK_ARGUMENTS = [
    '--ip', '0.0.0.0',
    '--port', '8888',
    '--notebook-dir',
    '/at_em_imaging_workflow/nb'
]

RENDER_SERVICE_URL = 'http://em-131db2.corp.alleninstitute.org'
RENDER_SERVICE_PORT = '8080'
RENDER_SERVICE_USER = 'gayathrim'
RENDER_SERVICE_PROJECT = 'DEV'
RENDER_STACK_NAME = 'default_stack'
RENDER_POINT_MATCH_COLLECTION_NAME = 'default_point_matches'
MATLAB_SOLVER_PATH='/allen/aibs/pipeline/image_processing/volume_assembly/EMAligner/dev/allen_templates'
MONTAGE_SOLVER_BIN=os.path.join(MATLAB_SOLVER_PATH, 'run_em_solver.sh')
RENDER_CLIENT_BASE_PATH='/allen/aibs/pipeline/image_processing/volume_assembly/render-jars/dev'
RENDER_CLIENT_SCRIPTS = os.path.join(RENDER_CLIENT_BASE_PATH, 'scripts')
RENDER_SPARK_JARFILE = os.path.join(RENDER_CLIENT_BASE_PATH, 'render-ws-spark-client-standalone.jar')
RENDER_CLIENT_JAR = os.path.join(RENDER_CLIENT_BASE_PATH, 'render-ws-java-client-standalone.jar')

FIJI_PATH = \
    '/allen/aibs/pipeline/image_processing/volume_assembly' + \
    '/Fiji.app/ImageJ-linux64'
SPARK_HOME='/allen/aibs/pipeline/image_processing/volume_assembly/utils/spark'
GRID_SIZE = 3
HEAP_SIZE = 10
INITIAL_SIGMA = 1.6
STEPS = 3
MIN_OCTAVE_SIZE = 800
MAX_OCTAVE_SIZE = 1200
FD_SIZE = 4
FD_BINS = 8

ROD = 0.92
MAX_EPSILON = 50
MIN_INLIER_RATIO = 0.0
MIN_NUMBER_INLIERS = 5
EXPECTED_MODEL_INDEX = 1
MULTIPLE_HYPOTHESES = True
REJECT_IDENTITY = True
IDENTITY_TOLERANCE = 5.0
TILES_ARE_IN_PLACE = True
DESIRED_MODEL_INDEX = 0
REGULARIZE = False
MAX_ITERATIONS_OPTIMIZE = 2000
MAX_PLATEAU_WIDTH_OPTIMIZE = 200
DIMENSION = 5
LAMBDA_VAL = 0.01
CLEAR_TRANSFORM = True
VISUALIZE = False

CHUNK_DEFAULTS = {
    'overlap': 100,
    'start_z': 1,
    'chunk_size': 1000
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qde=#m)tepmm$!n1j3+b8#!mz_s-pn2@2soe@9^_ol8363pjlp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

RESULTS_PER_PAGE = 20

MAX_DISPLAYED_PAGE_LINKS = 10

WORKFLOW_VERSION = 0.1

MILLISECONDS_BETWEEN_REFRESH = 10000
# MILLISECONDS_BETWEEN_REFRESH = 1000
MOAB_CHECK_SECONDS = 45.0
DASHBOARD_UPDATE_SECONDS = 60.0

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_fsm',
    'workflow_engine',
    'at_em_imaging_workflow'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = APP_PACKAGE + '.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'at_em_imaging_workflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'at_em_imaging_dev',
        'USER': 'timf',
        'PASSWORD': '6 Need a safe house',
        'HOST': 'aibsdc-dev-db1',
        'PORT': '5432',
    },
    'devdb2': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'at_em_imaging_dev',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'devdb2',
        'PORT': '5432',
    },
    'test': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(PROJECT_ROOT, 'database.db'),
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': ''
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'US/Pacific'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, APP_PACKAGE, 'static')
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed': {
            'class': 'logging.Formatter',
            'format': '%(asctime)s %(name)-15s %(levelname)-8s %(processName)-10s %(lineno)-5d %(message)s'
        }
    },    
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'detailed',
            'stream': 'ext://sys.stdout'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'detailed',
            'filename': os.environ.get('DEBUG_LOG', 'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARN',
            'propagate': True,
        },
        'at_em_imaging_workflow': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'test_output': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'workflow_client': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'workflow_engine': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'celery.task': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        }        
    }
} 
CELERYD_HIJACK_ROOT_LOGGER = True

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

